# coding: utf-8

"""
    Connected Product API

    This API bundle allows to collect usage data from different \"connected products\". A connected product is an IoT consumer product connected to the IoT platform through a digital interface. Possible connected products are: <ul> <li>natively connected products (e.g. smart kitchen appliances, smart coffee machines, smart fridge, etc.);</li> <li>regular products connected through a gateway and equipped with additional sensors (e.g. bags or luggages with NFC or Bluetooth tags, etc.)</li> </ul> <p>To register for the first time a new product, the <code>init</code> method must be invoked.</p> <p>After registration, every product usage event (e.g. state change, sensors value change, user interaction with the product, etc.) is sent to the platform using the <code>event</code> method. </p>  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Init(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'timestamp': 'int',
        'location': 'Location',
        'object_attributes': 'list[ObjectAttribute]'
    }

    attribute_map = {
        'timestamp': 'timestamp',
        'location': 'location',
        'object_attributes': 'objectAttributes'
    }

    def __init__(self, timestamp=None, location=None, object_attributes=None):  # noqa: E501
        """Init - a model defined in Swagger"""  # noqa: E501
        self._timestamp = None
        self._location = None
        self._object_attributes = None
        self.discriminator = None
        self.timestamp = timestamp
        if location is not None:
            self.location = location
        if object_attributes is not None:
            self.object_attributes = object_attributes

    @property
    def timestamp(self):
        """Gets the timestamp of this Init.  # noqa: E501

        The timestamp (in form of Unix Timestamp in milliseconds - see `https://currentmillis.com/` for clarifications) of the registration of the connected product  # noqa: E501

        :return: The timestamp of this Init.  # noqa: E501
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this Init.

        The timestamp (in form of Unix Timestamp in milliseconds - see `https://currentmillis.com/` for clarifications) of the registration of the connected product  # noqa: E501

        :param timestamp: The timestamp of this Init.  # noqa: E501
        :type: int
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")  # noqa: E501

        self._timestamp = timestamp

    @property
    def location(self):
        """Gets the location of this Init.  # noqa: E501


        :return: The location of this Init.  # noqa: E501
        :rtype: Location
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this Init.


        :param location: The location of this Init.  # noqa: E501
        :type: Location
        """

        self._location = location

    @property
    def object_attributes(self):
        """Gets the object_attributes of this Init.  # noqa: E501

        Array of name+value tuples containing additional info about the connected product  # noqa: E501

        :return: The object_attributes of this Init.  # noqa: E501
        :rtype: list[ObjectAttribute]
        """
        return self._object_attributes

    @object_attributes.setter
    def object_attributes(self, object_attributes):
        """Sets the object_attributes of this Init.

        Array of name+value tuples containing additional info about the connected product  # noqa: E501

        :param object_attributes: The object_attributes of this Init.  # noqa: E501
        :type: list[ObjectAttribute]
        """

        self._object_attributes = object_attributes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Init, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Init):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
