# coding: utf-8

"""
    Connected Product API

    This API bundle allows to collect usage data from different \"connected products\". A connected product is an IoT consumer product connected to the IoT platform through a digital interface. Possible connected products are: <ul> <li>natively connected products (e.g. smart kitchen appliances, smart coffee machines, smart fridge, etc.);</li> <li>regular products connected through a gateway and equipped with additional sensors (e.g. bags or luggages with NFC or Bluetooth tags, etc.)</li> </ul> <p>To register for the first time a new product, the <code>init</code> method must be invoked.</p> <p>After registration, every product usage event (e.g. state change, sensors value change, user interaction with the product, etc.) is sent to the platform using the <code>event</code> method. </p>  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Connected Product API",
    author_email="",
    url="",
    keywords=["Swagger", "Connected Product API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    This API bundle allows to collect usage data from different \&quot;connected products\&quot;. A connected product is an IoT consumer product connected to the IoT platform through a digital interface. Possible connected products are: &lt;ul&gt; &lt;li&gt;natively connected products (e.g. smart kitchen appliances, smart coffee machines, smart fridge, etc.);&lt;/li&gt; &lt;li&gt;regular products connected through a gateway and equipped with additional sensors (e.g. bags or luggages with NFC or Bluetooth tags, etc.)&lt;/li&gt; &lt;/ul&gt; &lt;p&gt;To register for the first time a new product, the &lt;code&gt;init&lt;/code&gt; method must be invoked.&lt;/p&gt; &lt;p&gt;After registration, every product usage event (e.g. state change, sensors value change, user interaction with the product, etc.) is sent to the platform using the &lt;code&gt;event&lt;/code&gt; method. &lt;/p&gt;  # noqa: E501
    """
)
