# coding: utf-8

# flake8: noqa

"""
    Connected Product API

    This API bundle allows to collect usage data from different \"connected products\". A connected product is an IoT consumer product connected to the IoT platform through a digital interface. Possible connected products are: <ul> <li>natively connected products (e.g. smart kitchen appliances, smart coffee machines, smart fridge, etc.);</li> <li>regular products connected through a gateway and equipped with additional sensors (e.g. bags or luggages with NFC or Bluetooth tags, etc.)</li> </ul> <p>To register for the first time a new product, the <code>init</code> method must be invoked.</p> <p>After registration, every product usage event (e.g. state change, sensors value change, user interaction with the product, etc.) is sent to the platform using the <code>event</code> method. </p>  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from connprod.api.event_api import EventApi
from connprod.api.init_api import InitApi
from connprod.api.user_product_api import UserProductApi
# import ApiClient
from connprod.api_client import ApiClient
from connprod.configuration import Configuration
# import models into sdk package
from connprod.models.error_response import ErrorResponse
from connprod.models.event import Event
from connprod.models.event_attribute import EventAttribute
from connprod.models.events import Events
from connprod.models.geo import Geo
from connprod.models.init import Init
from connprod.models.interaction import Interaction
from connprod.models.location import Location
from connprod.models.object_attribute import ObjectAttribute
from connprod.models.sensor import Sensor
from connprod.models.user_product import UserProduct
from connprod.models.user_products_response import UserProductsResponse
