# coding: utf-8

# flake8: noqa
"""
    Connected Product API

    This API bundle allows to collect usage data from different \"connected products\". A connected product is an IoT consumer product connected to the IoT platform through a digital interface. Possible connected products are: <ul> <li>natively connected products (e.g. smart kitchen appliances, smart coffee machines, smart fridge, etc.);</li> <li>regular products connected through a gateway and equipped with additional sensors (e.g. bags or luggages with NFC or Bluetooth tags, etc.)</li> </ul> <p>To register for the first time a new product, the <code>init</code> method must be invoked.</p> <p>After registration, every product usage event (e.g. state change, sensors value change, user interaction with the product, etc.) is sent to the platform using the <code>event</code> method. </p>  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.error_response import ErrorResponse
from swagger_client.models.event import Event
from swagger_client.models.event_attribute import EventAttribute
from swagger_client.models.events import Events
from swagger_client.models.geo import Geo
from swagger_client.models.init import Init
from swagger_client.models.interaction import Interaction
from swagger_client.models.location import Location
from swagger_client.models.object_attribute import ObjectAttribute
from swagger_client.models.sensor import Sensor
from swagger_client.models.user_product import UserProduct
from swagger_client.models.user_products_response import UserProductsResponse
